name: Automation Script

on:
  push:
    branches:
      - master

jobs:
  pipeline:
    name: Pipeline
    runs-on: ubuntu-20.04
    steps:
      - name: Initiating
        uses: actions/checkout@v1
      - name: Preparing GoLang
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.x'
      - name: Preparing Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Linting GoLang Core
        run: |
          cd core
          go get -u golang.org/x/lint/golint
          $(which golint 2> /dev/null || echo /home/$USER/go/bin/golint) -set_exit_status ./...
          cd ..
      - name: Testing GoLang Core
        run: |
          cd core
          go test ./...
          cd ..
      - name: Building GoLang Core
        run: |
          cd core
          GOOS=js GOARCH=wasm go build -o main.wasm
          cd ..
          cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" ui/public/
          cp core/main.wasm ui/public/
      - name: Building and Deploying Node.js UI
        run: |
          cd ui
          npm ci
          git config user.name $GITHUB_ACTOR
          git config user.email $GITHUB_ACTOR@users.noreply.github.com
          git checkout --orphan gh-pages
          npm run build
          git --work-tree dist add --all
          git --work-tree dist commit -m gh-pages
          git remote add github "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git push github HEAD:gh-pages --force
          rm -r dist
          git checkout -f master
          git branch -D gh-pages
          cd ..
